export const UPDATE_VIEW_COLLECTION = 'UPDATE_VIEW_COLLECTION';
export const LOAD_RECENT_BOOKS = 'LOAD_RECENT_BOOKS';
export const ADD_ITEM_TO_CART='ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART='REMOVE_ITEM_FROM_CART';
